---
title: "Untitled"
author: "Tianyi Zuo"
date: "2022/3/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(ggplot2)
library(ape)
library(ggtree)
library(vegan)
library(dplyr)
library(reshape2)
library(data.table)

```

```{r}
MBData<-read.csv("./Data/BacteriaCommunityMatrix.csv")
SBData<-read.csv("./Data/BacteriaSampleData.csv")
NBData<-read.csv("./Data/BacteriaTaxInfo.csv")
GData<-read.csv("./Data/GreenhouseData.csv")
```

```{r}
MatrixA <- select(MBData, X,starts_with("Ammophila"))
MatrixA <- MatrixA[grep("A_", MatrixA$X), ]

MatrixB <- select(MBData, X,starts_with("Baccharis"))
MatrixB <- MatrixB[grep("B_", MatrixB$X), ]

MatrixI <- select(MBData, X,starts_with("Iceplant"))
MatrixI <- MatrixI[grep("I_", MatrixI$X), ]

MatrixL <- select(MBData, X,starts_with("Lupine"))
MatrixL <- MatrixL[grep("L_", MatrixL$X), ]

rownames(MatrixA) <-MatrixA$X
MatrixA<-select(MatrixA,-X)

MatrixA<-MatrixA[rowSums(MatrixA[])>0,]
```

```{r}
Dist<- vegdist(MatrixA,method="bray",binary=F)
DistMat<-as.matrix(Dist)
PDat<-melt(DistMat)

set.seed(12138)
NMDSdat<-metaMDS(Dist,k=3  ,trymax = 50)
```
```{r}
PDat<-data.frame(NMDS1=NMDSdat$points[,1],
                 NMDS2=NMDSdat$points[,2],
                 X=row.names(MatrixA))
```

```{r}
PDat<-merge(PDat,NBData,by="X",all.x=T,all.y=F)
qplot(x=NMDS1,y=NMDS2,colour=Phylum,alpha=I(0.6),data=PDat)+theme_bw()
```

